spring:
  # 环境 dev|test|prod
  profiles:
    active: dev

  application:
    name: netty-server

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.leiman.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1        #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0     # 逻辑未删除值(默认为 0)
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
    cache-enabled: false       #二级缓存
    call-setters-on-nulls: true  #为空也返回
    jdbc-type-for-null: 'null'   #插入空值不报错

logging:
  config: classpath:logback-spring.xml

netty:
  port: 8888 #netty Server 端口